version: "3.3"

services:
  client:
    build:
      context: ./client
  backend:
    build:
      context: ./server
    environment:
      - APP_PORT=${BACKEND_PORT}
      - APP_HOST=0.0.0.0
      - SECRET_KEY=${SECRET_KEY}
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
      - LOGGING_DIR=logs
      - LOGGING_LEVEL=debug
    command: ["npm", "run", "start"]
    restart: always
