version: "3.3"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    environment:
      - BACKEND_HOST=backend
      - BACKEND_PORT=5000
    volumes:
      - /app/node_modules
      - ./client:/app
    restart: on-failure
    command: ["npm", "run", "dev"]
  backend:
    build:
      context: ./server
    environment:
      - APP_PORT=${BACKEND_PORT}
      - APP_HOST=0.0.0.0
      - SECRET_KEY=${SECRET_KEY}
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
      - LOGGING_DIR=logs
      - LOGGING_LEVEL=debug
    command: ["npm", "run", "watch"]
    volumes:
      - /app/node_modules
      - ./server:/app
  nginx:
    depends_on:
      - client
      - backend
